### PR TITLE
task/HTML: initial commit

### PR DESCRIPTION
**Pull request by riorasyid23**
Mengerjakan Summary dan Task HTML Nomor 1,2,3

### CODE REVIEW

**Review by syukronarie — COMMENTED** [review]
kurang tugasnya

**Comment by riorasyid23** [comment]
> kurang tugasnya

Ashiap

**Comment by riorasyid23** [comment]
Penambahan Summary dan Pengerjaan Essay

- [x] Summary
- [x] index.html
- [x] form.html
- [x] welcome.html

**Review by syukronarie — APPROVED** [review]
Reviewed. Tks

**Pull request merged**
